language: node_js
node_js:
  - 12
os:
  - linux
dist: bionic

before_install:
  - sudo apt-get -y install pandoc
install:
  - yarn install
script: 
  - yarn build

# Publish the website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
