language: node_js
node_js:
  - 12
os:
  - linux
dist: bionic

before_install:
  - curl -o ./pandoc.deb -L "https://github.com/jgm/pandoc/releases/download/2.10/pandoc-2.10-1-amd64.deb"
  - sudo apt-get -y install ./pandoc.deb
install:
  - yarn install
script: 
  - yarn build

# Publish the website
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
