# https://taskfile.dev

version: '2'

vars:
  SERVER: ptalley2@linux.oit.utk.edu
  HTML_ROOT: ~/public_html

tasks:
  publish:
    cmds:
      - yarn build
      - tar -caf dist.tar.gz dist
      - scp dist.tar.gz {{.SERVER}}:{{.HTML_ROOT}}
      - ssh {{.SERVER}} "cd {{.HTML_ROOT}}; tar -xaf dist.tar.gz; rm -r model-viewer; mv dist model-viewer; rm dist.tar.gz"
      - rm dist.tar.gz
    silent: true
